# Generated by Django 2.2.7 on 2019-12-01 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperative_name', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'ordering': ['cooperative_name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=5)),
                ('cooperative_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                     related_name='cooperative_id', to='base.Cooperative')),
            ],
            options={
                'ordering': ['cooperative_id', 'unit_number'],
            },
        ),
    ]
