# Generated by Django 2.2.7 on 2019-11-25 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=5)),
                ('cooperative_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                     to='base.Cooperative')),
            ],
            options={
                'ordering': ['cooperative_id', 'unit_number'],
            },
        ),
    ]
