# Generated by Django 2.2.7 on 2019-11-25 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='cooperative_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooperative_id',
                                    to='base.Cooperative'),
        ),
    ]
