# Generated by Django 2.2.5 on 2019-12-10 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(choices=[('CREATE_COOP', 'Create Cooperative Housing')], max_length=15)),
                ('note', models.CharField(max_length=255, null=True)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True,
                                                                              verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True,
                                                                                   verbose_name='modified')),
                ('message_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                   related_name='message_from', to=settings.AUTH_USER_MODEL)),
                ('message_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='message_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
