# Generated by Django 2.2.5 on 2019-12-11 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='request',
            new_name='task',
        ),
    ]
