# Generated by Django 2.2.5 on 2019-12-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_auto_20191211_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
