# Generated by Django 2.2.5 on 2019-12-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_message_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='done',
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('DONE', 'Done'), ('REJECT', 'Reject')], default='OPEN',
                                   max_length=6),
        ),
    ]
